# Generated by Django 6.1.1 on 2026-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='назва акції')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('birthday', 'Знижка на день народження'), ('subscription', "М'ясний абонемент"), ('cheese_friday', "Сирна п'ятниця"), ('free_coffee', 'Кава в подарунок'), ('other', 'Інша акція')], default='other', max_length=30, verbose_name='тип акції')),
                ('description', models.TextField(blank=True, default='', verbose_name='опис')),
                ('badge', models.CharField(blank=True, default='', max_length=50, verbose_name='текст бейджа')),
                ('badge_color', models.CharField(blank=True, default='', max_length=30, verbose_name='колір бейджа')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок сортування')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
            ],
            options={
                'verbose_name': 'акція',
                'verbose_name_plural': 'акції',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
