# Generated by Django 6.1.1 on 2026-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
