# Generated by Django 6.1.1 on 2026-10-01 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='назва')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('emoji', models.CharField(blank=True, default='', max_length=20, verbose_name='emoji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'категорія',
                'verbose_name_plural': 'категорії',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='зовнішній ID')),
                ('name', models.CharField(max_length=255, verbose_name='назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ціна')),
                ('price_display', models.CharField(blank=True, default='', max_length=60, verbose_name='відображення ціни')),
                ('unit', models.CharField(default='кг', max_length=20, verbose_name='одиниця вимірювання')),
                ('emoji', models.CharField(blank=True, default='', max_length=20, verbose_name='emoji')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='зображення')),
                ('is_available', models.BooleanField(default=True, verbose_name='в наявності')),
                ('is_featured', models.BooleanField(default=False, verbose_name='рекомендований')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='залишок на складі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='категорія')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товари',
                'ordering': ['-is_featured', 'name'],
            },
        ),
    ]
