# Generated by Django 6.1.1 on 2026-10-01 13:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='ключ сесії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'кошик',
                'verbose_name_plural': 'кошики',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='імʼя клієнта')),
                ('phone', models.CharField(max_length=30, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='місто')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='адреса доставки')),
                ('comment', models.TextField(blank=True, default='', verbose_name='коментар')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('confirmed', 'Підтверджено'), ('processing', 'В обробці'), ('shipping', 'Доставляється'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='new', max_length=20, verbose_name='статус')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='загальна сума')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='знижка')),
                ('final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='сума до сплати')),
                ('is_quick', models.BooleanField(default=False, verbose_name='швидке замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'замовлення',
                'verbose_name_plural': 'замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='назва товару (снепшот)')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ціна товару (снепшот)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('unit', models.CharField(default='кг', max_length=20, verbose_name='одиниця вимірювання')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='замовлення')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'позиція замовлення',
                'verbose_name_plural': 'позиції замовлення',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='кошик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'позиція кошика',
                'verbose_name_plural': 'позиції кошика',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
